const TrophiesMasterList = [
	{id: "0" , trophy_data : { Title: 'Trophy 1', Description: 'Ate a carrot', ImageIcon: 'nutrition', Color: '#FB8B24'}}, 
	{id: "1", trophy_data : { Title: 'Trophy 2', Description: 'Ate a carrot', ImageIcon: 'bonfire', Color: '#9A031E'}},
	{id: "2", trophy_data : { Title: 'Trophy 3', Description: 'Ate a carrot', ImageIcon: 'compass', Color: '#EDC9FF'}},
	{id: "3", trophy_data : { Title: 'Trophy 4', Description: 'Ate a carrot', ImageIcon: 'basket', Color: '#D8B4A0'}},
	{id: "4", trophy_data : { Title: 'Trophy 5', Description: 'Ate a carrot', ImageIcon: 'basketball', Color: '#C75000'}},
	{id: "5", trophy_data : { Title: 'Trophy 6', Description: 'Ate a carrot', ImageIcon: 'boat', Color: '#7678ED'}},
	{id: "6", trophy_data : { Title: 'Trophy 7', Description: 'Ate a carrot', ImageIcon: 'flask', Color: '#6A0F49'}},
	{id: "7", trophy_data : { Title: 'Trophy 8', Description: 'Ate a carrot', ImageIcon: 'leaf', Color: '#ACE4AA'}},
	{id: "8", trophy_data : { Title: 'Trophy 9', Description: 'Ate a carrot', ImageIcon: 'color-palette', Color: '#F2758F'}},
	{id: "9", trophy_data : { Title: 'Trophy 10', Description: 'Ate a carrot', ImageIcon: 'ice-cream', Color: '#5BC0BE'}},
	{id: "10", trophy_data : { Title: 'Trophy 11', Description: 'Ate a carrot', ImageIcon: 'jet', Color: '#70928B'}},
	{id: "11", trophy_data : { Title: 'Trophy 12', Description: 'Ate a carrot', ImageIcon: 'magnet', Color: '#F03A47'}},
	{id: "12", trophy_data : { Title: 'Trophy 13', Description: 'Ate a carrot', ImageIcon: 'megaphone', Color: '#0F4C5C'}},
	{id: "13", trophy_data : { Title: 'Trophy 14', Description: 'Ate a carrot', ImageIcon: 'planet', Color: '#7D5BA6'}},
	{id: "14", trophy_data : { Title: 'Trophy 15', Description: 'Ate a carrot', ImageIcon: 'color-wand', Color: '#BC9EC1'}},
	{id: "15", trophy_data : { Title: 'Trophy 16', Description: 'Ate a carrot', ImageIcon: 'star', Color: '#F7B801'}},
	{id: "16", trophy_data : { Title: 'Trophy 17', Description: 'Ate a carrot', ImageIcon: 'paw', Color: '#AF5B5B'}},
	{id: "17", trophy_data : { Title: 'Trophy 18', Description: 'Ate a carrot', ImageIcon: 'moon', Color: '#97EFE9'}},
	{id: "18", trophy_data : { Title: 'Trophy 19', Description: 'Ate a carrot', ImageIcon: 'pizza', Color: '#EC866B'}},
	{id: "19", trophy_data : { Title: 'Trophy 20', Description: 'Ate a carrot', ImageIcon: 'rainy', Color: '#276FBF'}},
	{id: "20", trophy_data : { Title: 'Trophy 21', Description: 'Ate a carrot', ImageIcon: 'snow', Color: '#B0CAE7'}},

]
export default TrophiesMasterList; 