const TrophiesMasterList = [
	{id: "0" , trophy_data : { Title: '1 Carrot', Description: 'Ate a carrot', ImageIcon: 'nutrition', Color: '#FB8B24'}}, 
	{id: "1", trophy_data : { Title: '2 Carrot', Description: 'Ate a carrot', ImageIcon: 'bonfire', Color: '#9A031E'}},
	{id: "2", trophy_data : { Title: '3 Carrot', Description: 'Ate a carrot', ImageIcon: 'compass', Color: '#EDC9FF'}},
	{id: "3", trophy_data : { Title: '4 Carrot', Description: 'Ate a carrot', ImageIcon: 'basket', Color: '#D8B4A0'}},
	{id: "4", trophy_data : { Title: '5 Carrot', Description: 'Ate a carrot', ImageIcon: 'basketball', Color: '#C75000'}},
	{id: "5", trophy_data : { Title: '6 Carrot', Description: 'Ate a carrot', ImageIcon: 'boat', Color: '#7678ED'}},
	{id: "6", trophy_data : { Title: '7 Carrot', Description: 'Ate a carrot', ImageIcon: 'flask', Color: '#6A0F49'}},
	{id: "7", trophy_data : { Title: '8 Carrot', Description: 'Ate a carrot', ImageIcon: 'leaf', Color: '#ACE4AA'}},
	{id: "8", trophy_data : { Title: '9 Carrot', Description: 'Ate a carrot', ImageIcon: 'color-palette', Color: '#F2758F'}},
	{id: "9", trophy_data : { Title: '10 Carrot', Description: 'Ate a carrot', ImageIcon: 'ice-cream', Color: '#5BC0BE'}},
	{id: "10", trophy_data : { Title: '11 Carrot', Description: 'Ate a carrot', ImageIcon: 'jet', Color: '#70928B'}},
	{id: "11", trophy_data : { Title: '12 Carrot', Description: 'Ate a carrot', ImageIcon: 'magnet', Color: '#F03A47'}},
	{id: "12", trophy_data : { Title: '13 Carrot', Description: 'Ate a carrot', ImageIcon: 'megaphone', Color: '#0F4C5C'}},
	{id: "13", trophy_data : { Title: '14 Carrot', Description: 'Ate a carrot', ImageIcon: 'planet', Color: '#7D5BA6'}},
	{id: "14", trophy_data : { Title: '15 Carrot', Description: 'Ate a carrot', ImageIcon: 'color-wand', Color: '#BC9EC1'}},
	{id: "15", trophy_data : { Title: '16 Carrot', Description: 'Ate a carrot', ImageIcon: 'star', Color: '#F7B801'}},
	{id: "16", trophy_data : { Title: '17 Carrot', Description: 'Ate a carrot', ImageIcon: 'paw', Color: '#AF5B5B'}},
	{id: "17", trophy_data : { Title: '18 Carrot', Description: 'Ate a carrot', ImageIcon: 'moon', Color: '#97EFE9'}},
	{id: "18", trophy_data : { Title: '19 Carrot', Description: 'Ate a carrot', ImageIcon: 'pizza', Color: '#EC866B'}},
	{id: "19", trophy_data : { Title: '20 Carrot', Description: 'Ate a carrot', ImageIcon: 'rainy', Color: '#276FBF'}},
	{id: "20", trophy_data : { Title: '21 Carrot', Description: 'Ate a carrot', ImageIcon: 'snow', Color: '#B0CAE7'}},

]
export default TrophiesMasterList; 